/**
 * src/publish/ds-site-v2/scripts/build-tokens.ts
 *
 * Reads ledger/tokens.json and emits:
 *   - app/tokens.css             — CSS custom properties under :root (and dark)
 *   - lib/tokens.generated.ts    — typed TypeScript manifest consumed by pages
 *
 * This is the FIRST cut. The taxonomy migration (TDR-0001) is still pending
 * review, so the script consumes the CURRENT ledger shape (legacy names:
 * color.001, typography.01, etc.) and emits CSS variables prefixed --bc-.
 * Semantic aliases will layer on top once TDR-0001 is accepted.
 *
 * Usage: pnpm build:tokens    (auto-run by `pnpm dev` and `pnpm build`)
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import type { LedgerState, LedgerToken, Surface } from '../../../types/index.js'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const SITE_ROOT = path.resolve(HERE, '..')
const REPO_ROOT = path.resolve(SITE_ROOT, '..', '..', '..')
const LEDGER_PATH = path.join(REPO_ROOT, 'ledger', 'tokens.json')
const TOKENS_CSS_OUT = path.join(SITE_ROOT, 'app', 'tokens.css')
const TOKENS_TS_OUT  = path.join(SITE_ROOT, 'lib', 'tokens.generated.ts')

// ─── Color math + classification (mirrors src/publish/ds-site/build.ts) ──────

function isAlphaHex(v: string): boolean { return /^#[0-9a-f]{8}$/i.test(v) }
function solidOf(v: string): string { return isAlphaHex(v) ? '#' + v.slice(1, 7) : v }

function hexToHsl(hex: string): { h: number; s: number; l: number } {
  const h = hex.replace('#', '').slice(0, 6)
  const r = parseInt(h.slice(0, 2), 16) / 255
  const g = parseInt(h.slice(2, 4), 16) / 255
  const b = parseInt(h.slice(4, 6), 16) / 255
  const max = Math.max(r, g, b), min = Math.min(r, g, b), d = max - min
  const L = (max + min) / 2
  const S = d === 0 ? 0 : (L > 0.5 ? d / (2 - max - min) : d / (max + min))
  let H = 0
  if (d) {
    if (max === r) H = ((g - b) / d) % 6
    else if (max === g) H = (b - r) / d + 2
    else H = (r - g) / d + 4
    H = H * 60
    if (H < 0) H += 360
  }
  return { h: H, s: S * 100, l: L * 100 }
}
function luminance(hex: string): number {
  const h = solidOf(hex).replace('#', '')
  const r = parseInt(h.slice(0, 2), 16) / 255
  const g = parseInt(h.slice(2, 4), 16) / 255
  const b = parseInt(h.slice(4, 6), 16) / 255
  return 0.2126 * r + 0.7152 * g + 0.0722 * b
}

type ColorCategory = 'brand' | 'neutral' | 'feedback' | 'overlay' | 'surface' | 'interactive' | 'course'
type FeedbackRole = 'danger' | 'warning' | 'success' | 'info'

const BRAND_HEXES = new Set(['#4e3bc2', '#6651e4', '#4d3bc2', '#1a237e', '#0d47a1'])
const NEUTRAL_L_FLOOR = 5
const NEUTRAL_L_CEILING = 97

function classifyColor(t: LedgerToken): ColorCategory {
  if (t.name.startsWith('color/course/')) return 'course'
  if (t.name.startsWith('color/interactive/')) return 'interactive'
  if (t.name.startsWith('color/overlay/')) return 'overlay'
  if (t.name.startsWith('color/surface/')) return 'surface'
  const v = t.value.toLowerCase()
  if (isAlphaHex(v)) return 'overlay'
  if (BRAND_HEXES.has(v)) return 'brand'
  const hsl = hexToHsl(v)
  if (hsl.l < NEUTRAL_L_FLOOR || hsl.l > NEUTRAL_L_CEILING) return 'neutral'
  if (hsl.s < 15) return 'neutral'
  if (hsl.l > 92) return 'surface'
  if (hsl.h >= 240 && hsl.h <= 280 && hsl.s >= 35) return 'brand'
  return 'feedback'
}

function feedbackRoleOf(hex: string): FeedbackRole {
  const { h } = hexToHsl(solidOf(hex))
  if (h >= 340 || h < 20) return 'danger'
  if (h >= 20 && h < 70) return 'warning'
  if (h >= 70 && h < 170) return 'success'
  return 'info'
}

// ─── CSS variable name generation ────────────────────────────────────────────

function cssVarName(tokenName: string): string {
  // color.008 → --bc-color-008; color/overlay/dark → --bc-color-overlay-dark
  return '--bc-' + tokenName.replace(/[./]/g, '-')
}

// ─── Token shape we emit into lib/tokens.generated.ts ────────────────────────

interface GeneratedColorToken {
  name: string
  value: string
  cssVar: string
  category: ColorCategory
  feedbackRole?: FeedbackRole
  description?: string
  usageCount: number
  confidence: number
  tier: 'canonical' | 'candidate' | 'deprecated'
  surfaces: Surface[]
  pages: string[]
}

// ─── Main build ──────────────────────────────────────────────────────────────

function build(): void {
  const raw = readFileSync(LEDGER_PATH, 'utf-8')
  const ledger = JSON.parse(raw) as LedgerState

  const canonical = ledger.tokens.filter(t => t.canonical)
  const colorTokens = canonical.filter(t => t.type === 'color')

  // ── 1. CSS variables ──
  const cssLines: string[] = []
  cssLines.push('/**')
  cssLines.push(' * AUTO-GENERATED by scripts/build-tokens.ts. DO NOT EDIT.')
  cssLines.push(` * Source: ledger/tokens.json (${canonical.length} canonical tokens · ${ledger.lastBuilt.slice(0, 10)})`)
  cssLines.push(' */')
  cssLines.push('')
  cssLines.push(':root {')
  for (const t of canonical) {
    cssLines.push(`  ${cssVarName(t.name)}: ${t.value};`)
  }
  cssLines.push('}')
  cssLines.push('')
  cssLines.push('/* Dark theme: until a dark ledger exists, dark inherits light values. */')
  cssLines.push("[data-theme='dark'] {")
  cssLines.push('  /* Overrides will land here once TDR-0001 introduces dark-mode primitives. */')
  cssLines.push('}')
  cssLines.push('')
  writeFileSync(TOKENS_CSS_OUT, cssLines.join('\n'))

  // ── 2. Typed TS manifest ──
  const generatedColors: GeneratedColorToken[] = colorTokens.map(t => {
    const category = classifyColor(t)
    const token: GeneratedColorToken = {
      name: t.name,
      value: t.value,
      cssVar: cssVarName(t.name),
      category,
      usageCount: t.usageCount ?? 0,
      confidence: t.confidence,
      tier: t.confidence >= 0.9 ? 'canonical' : t.confidence >= 0.4 ? 'candidate' : 'deprecated',
      surfaces: (t.surfaces && t.surfaces.length > 0) ? t.surfaces : [t.surface],
      pages: t.pages ?? [],
    }
    if (category === 'feedback') token.feedbackRole = feedbackRoleOf(solidOf(t.value))
    // Propagate description from ledger (manual-canonicals or synthesized)
    const desc = t.description ?? (t.raw as Record<string, unknown> | undefined)?.['description'] as string | undefined
    if (desc) token.description = desc
    return token
  })

  // Group + sort per category for the UI
  const byCategory = {
    brand:       generatedColors.filter(c => c.category === 'brand').sort((a, b) => b.usageCount - a.usageCount),
    neutral:     generatedColors.filter(c => c.category === 'neutral').sort((a, b) => luminance(b.value) - luminance(a.value)),
    feedback: {
      danger:  generatedColors.filter(c => c.category === 'feedback' && c.feedbackRole === 'danger').sort((a, b) => b.usageCount - a.usageCount),
      warning: generatedColors.filter(c => c.category === 'feedback' && c.feedbackRole === 'warning').sort((a, b) => b.usageCount - a.usageCount),
      success: generatedColors.filter(c => c.category === 'feedback' && c.feedbackRole === 'success').sort((a, b) => b.usageCount - a.usageCount),
      info:    generatedColors.filter(c => c.category === 'feedback' && c.feedbackRole === 'info').sort((a, b) => b.usageCount - a.usageCount),
    },
    surface: generatedColors.filter(c => c.category === 'surface').sort((a, b) => luminance(b.value) - luminance(a.value)),
    overlay: generatedColors.filter(c => c.category === 'overlay').sort((a, b) => {
      const aA = isAlphaHex(a.value) ? parseInt(a.value.slice(-2), 16) : 255
      const bA = isAlphaHex(b.value) ? parseInt(b.value.slice(-2), 16) : 255
      return aA - bA
    }),
    interactive: generatedColors.filter(c => c.category === 'interactive'),
    course: generatedColors.filter(c => c.category === 'course').sort((a, b) => {
      // Sort by course name (from token path), then by shade (luminance)
      if (a.name < b.name) return -1
      if (a.name > b.name) return 1
      return 0
    }),
  }

  // ── 2b. Typography tokens ──
  interface GeneratedTypoToken {
    name: string
    value: string
    cssVar: string
    family: string
    size: number
    weight: number
    lineHeight: number | null
    letterSpacing: number | null
    usageCount: number
    confidence: number
    tier: 'canonical' | 'candidate' | 'deprecated'
    role: 'display' | 'heading' | 'body' | 'caption'
  }

  const typoTokens = canonical.filter(t => t.type === 'typography')
  const generatedTypo: GeneratedTypoToken[] = typoTokens
    .map(t => {
      let sig: { fontFamily?: string | null; fontSize?: number | null; fontWeight?: number | null; lineHeightPx?: number | null; letterSpacing?: number | null }
      try { sig = JSON.parse(t.value) } catch { return null }
      const size = sig.fontSize ?? 16
      const weight = sig.fontWeight ?? 400
      let role: GeneratedTypoToken['role'] = 'body'
      if (size >= 20) role = 'display'
      else if (weight >= 600 && size >= 16) role = 'heading'
      else if (size <= 12) role = 'caption'
      return {
        name: t.name,
        value: t.value,
        cssVar: cssVarName(t.name),
        family: sig.fontFamily ?? 'Nunito',
        size,
        weight,
        lineHeight: sig.lineHeightPx ?? null,
        letterSpacing: sig.letterSpacing ?? null,
        usageCount: t.usageCount ?? 0,
        confidence: t.confidence,
        tier: (t.confidence >= 0.9 ? 'canonical' : t.confidence >= 0.4 ? 'candidate' : 'deprecated') as GeneratedTypoToken['tier'],
        role,
      }
    })
    .filter((t): t is GeneratedTypoToken => t !== null)
    .sort((a, b) => {
      if (a.size !== b.size) return a.size - b.size
      return a.weight - b.weight
    })

  const typoSizes = [...new Set(generatedTypo.map(t => t.size))].sort((a, b) => a - b)
  const typoWeights = [...new Set(generatedTypo.map(t => t.weight))].sort((a, b) => a - b)

  const tsLines: string[] = []
  tsLines.push('/**')
  tsLines.push(' * AUTO-GENERATED by scripts/build-tokens.ts. DO NOT EDIT.')
  tsLines.push(` * Source: ledger/tokens.json (${ledger.lastBuilt.slice(0, 10)})`)
  tsLines.push(' */')
  tsLines.push('')
  tsLines.push('export type ColorCategory = "brand" | "neutral" | "feedback" | "overlay" | "surface" | "interactive" | "course"')
  tsLines.push('export type FeedbackRole = "danger" | "warning" | "success" | "info"')
  tsLines.push('export type Tier = "canonical" | "candidate" | "deprecated"')
  tsLines.push('')
  tsLines.push('export interface ColorToken {')
  tsLines.push('  name: string')
  tsLines.push('  value: string')
  tsLines.push('  cssVar: string')
  tsLines.push('  category: ColorCategory')
  tsLines.push('  feedbackRole?: FeedbackRole')
  tsLines.push('  description?: string')
  tsLines.push('  usageCount: number')
  tsLines.push('  confidence: number')
  tsLines.push('  tier: Tier')
  tsLines.push('  surfaces: string[]')
  tsLines.push('  pages: string[]')
  tsLines.push('}')
  tsLines.push('')
  tsLines.push('export const colors: ColorToken[] = ' + JSON.stringify(generatedColors, null, 2) + ' as const satisfies ColorToken[]')
  tsLines.push('')
  tsLines.push('export const colorsByCategory = {')
  tsLines.push(`  brand:   colors.filter(c => c.category === "brand")   .sort((a,b) => b.usageCount - a.usageCount),`)
  tsLines.push(`  neutral: colors.filter(c => c.category === "neutral") ,`)
  tsLines.push(`  feedback: {`)
  tsLines.push(`    danger:  colors.filter(c => c.category === "feedback" && c.feedbackRole === "danger" ),`)
  tsLines.push(`    warning: colors.filter(c => c.category === "feedback" && c.feedbackRole === "warning"),`)
  tsLines.push(`    success: colors.filter(c => c.category === "feedback" && c.feedbackRole === "success"),`)
  tsLines.push(`    info:    colors.filter(c => c.category === "feedback" && c.feedbackRole === "info"   ),`)
  tsLines.push(`  },`)
  tsLines.push(`  surface:     colors.filter(c => c.category === "surface"),`)
  tsLines.push(`  overlay:     colors.filter(c => c.category === "overlay"),`)
  tsLines.push(`  interactive: colors.filter(c => c.category === "interactive"),`)
  tsLines.push(`  course:      colors.filter(c => c.category === "course"),`)
  tsLines.push('}')
  tsLines.push('')
  // Typography
  tsLines.push('export type TypoRole = "display" | "heading" | "body" | "caption"')
  tsLines.push('')
  tsLines.push('export interface TypographyToken {')
  tsLines.push('  name: string')
  tsLines.push('  value: string')
  tsLines.push('  cssVar: string')
  tsLines.push('  family: string')
  tsLines.push('  size: number')
  tsLines.push('  weight: number')
  tsLines.push('  lineHeight: number | null')
  tsLines.push('  letterSpacing: number | null')
  tsLines.push('  description?: string')
  tsLines.push('  usageCount: number')
  tsLines.push('  confidence: number')
  tsLines.push('  tier: Tier')
  tsLines.push('  role: TypoRole')
  tsLines.push('}')
  tsLines.push('')
  tsLines.push('export const typographyTokens: TypographyToken[] = ' + JSON.stringify(generatedTypo, null, 2) + ' as const satisfies TypographyToken[]')
  tsLines.push('')
  tsLines.push(`export const typoSizes = ${JSON.stringify(typoSizes)} as const`)
  tsLines.push(`export const typoWeights = ${JSON.stringify(typoWeights)} as const`)
  tsLines.push('')

  tsLines.push(`export const metadata = {`)
  tsLines.push(`  generatedAt: ${JSON.stringify(new Date().toISOString())},`)
  tsLines.push(`  ledgerLastBuilt: ${JSON.stringify(ledger.lastBuilt)},`)
  tsLines.push(`  totalCanonical: ${canonical.length},`)
  tsLines.push(`  totalColors: ${colorTokens.length},`)
  tsLines.push(`  totalTypography: ${generatedTypo.length},`)
  tsLines.push(`} as const`)
  tsLines.push('')

  // Ensure output dirs exist
  mkdirSync(path.dirname(TOKENS_CSS_OUT), { recursive: true })
  mkdirSync(path.dirname(TOKENS_TS_OUT), { recursive: true })
  writeFileSync(TOKENS_TS_OUT, tsLines.join('\n'))

  // ── Report ──
  console.log('[build-tokens] Source: ' + LEDGER_PATH)
  console.log(`[build-tokens] ${canonical.length} canonical tokens (${colorTokens.length} colors, ${generatedTypo.length} typography)`)
  console.log('[build-tokens] By category:')
  console.log(`    brand       ${byCategory.brand.length}`)
  console.log(`    neutral     ${byCategory.neutral.length}`)
  console.log(`    feedback    ${Object.values(byCategory.feedback).reduce((n, x) => n + x.length, 0)} (danger ${byCategory.feedback.danger.length}, warning ${byCategory.feedback.warning.length}, success ${byCategory.feedback.success.length}, info ${byCategory.feedback.info.length})`)
  console.log(`    surface     ${byCategory.surface.length}`)
  console.log(`    overlay     ${byCategory.overlay.length}`)
  console.log(`    interactive ${byCategory.interactive.length}`)
  console.log(`    course      ${byCategory.course.length}`)
  console.log(`[build-tokens] ✓ ${path.relative(REPO_ROOT, TOKENS_CSS_OUT)}`)
  console.log(`[build-tokens] ✓ ${path.relative(REPO_ROOT, TOKENS_TS_OUT)}`)
}

build()
