/**
 * src/publish/css-tokens.ts
 *
 * Generates tokens.css from the canonical ledger.
 * Output: a flat CSS file with custom properties for all approved tokens.
 *
 * Encoding rules (see ADR-0008):
 *   - colors: emitted verbatim as hex (#rrggbb or #rrggbbaa)
 *   - typography: per-property vars (family/size/weight/line-height/letter-spacing)
 *     The ledger stores typography as a JSON signature; this publisher decodes
 *     it into five addressable CSS variables per token.
 *   - shadows: emitted as valid CSS shadow strings with px values rounded to 1dp
 *
 * Usage: npm run publish:css
 */

import { readFileSync, writeFileSync } from 'fs'
import path from 'path'
import 'dotenv/config'
import type { LedgerState, LedgerToken } from '../types/index.js'

const LEDGER_DIR = 'ledger'
const PX_DECIMALS = 1

function tokenNameToCssVar(name: string): string {
  return `--bc-${name.replace(/\./g, '-')}`
}

function roundPx(n: number): string {
  const rounded = Number(n.toFixed(PX_DECIMALS))
  // Strip trailing .0 for cleanliness: 4.0 → 4
  return Number.isInteger(rounded) ? String(rounded) : String(rounded)
}

// ─── Typography: decode JSON signature into per-property CSS vars ─────────────

interface TypoSig {
  fontFamily?: string | null
  fontWeight?: number | null
  fontSize?: number | null
  lineHeightPx?: number | null
  letterSpacing?: number | null
}

function emitTypographyLines(token: LedgerToken): string[] {
  let sig: TypoSig = {}
  try { sig = JSON.parse(token.value) as TypoSig } catch { return [`  /* ${token.name}: unparsable value */`] }
  const base = tokenNameToCssVar(token.name)
  const lines: string[] = []
  if (sig.fontFamily) lines.push(`  ${base}-family: ${sig.fontFamily};`)
  if (sig.fontSize !== null && sig.fontSize !== undefined) lines.push(`  ${base}-size: ${roundPx(sig.fontSize)}px;`)
  if (sig.fontWeight !== null && sig.fontWeight !== undefined) lines.push(`  ${base}-weight: ${sig.fontWeight};`)
  if (sig.lineHeightPx !== null && sig.lineHeightPx !== undefined) lines.push(`  ${base}-line-height: ${roundPx(sig.lineHeightPx)}px;`)
  if (sig.letterSpacing !== null && sig.letterSpacing !== undefined) lines.push(`  ${base}-letter-spacing: ${roundPx(sig.letterSpacing)}px;`)
  return lines
}

// ─── Shadow: round px values to 1 decimal, preserve structure ─────────────────

function formatShadow(value: string): string {
  // Split multi-layer shadows, round each, rejoin
  return value.split(/,\s*/).map(layer => {
    // Match: [inset ]Xpx Ypx Bpx Spx #color
    const m = layer.trim().match(/^(inset\s+)?(-?\d+\.?\d*)px\s+(-?\d+\.?\d*)px\s+(-?\d+\.?\d*)px\s+(-?\d+\.?\d*)px\s+(#[0-9a-fA-F]+)$/)
    if (!m) return layer  // pass through unparseable layers
    const [, inset, x, y, blur, spread, color] = m
    return `${inset ?? ''}${roundPx(parseFloat(x!))}px ${roundPx(parseFloat(y!))}px ${roundPx(parseFloat(blur!))}px ${roundPx(parseFloat(spread!))}px ${color}`
  }).join(', ')
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  let ledger: LedgerState
  try {
    const raw = readFileSync(path.join(LEDGER_DIR, 'tokens.json'), 'utf-8')
    ledger = JSON.parse(raw) as LedgerState
  } catch {
    console.error('[publish:css] Ledger not found. Run npm run ledger:build first.')
    process.exit(1)
  }

  const approvedTokens = ledger.tokens.filter(
    t => !t.deprecated && t.confidence >= 0.8
  )

  const byType = new Map<string, LedgerToken[]>()
  for (const token of approvedTokens) {
    const existing = byType.get(token.type) ?? []
    existing.push(token)
    byType.set(token.type, existing)
  }

  const lines: string[] = [
    '/**',
    ' * BrightChamps Design System — CSS Custom Properties',
    ` * Generated: ${new Date().toISOString()}`,
    ` * Ledger version: ${ledger.version}`,
    ' * DO NOT EDIT MANUALLY — generated by npm run publish:css',
    ' */',
    '',
    ':root {',
  ]

  let varCount = 0
  for (const [type, tokens] of byType) {
    lines.push(`  /* ${type.toUpperCase()} */`)
    for (const token of tokens) {
      if (type === 'typography') {
        const typoLines = emitTypographyLines(token)
        lines.push(...typoLines)
        varCount += typoLines.length
      } else if (type === 'shadow') {
        lines.push(`  ${tokenNameToCssVar(token.name)}: ${formatShadow(token.value)};`)
        varCount++
      } else {
        lines.push(`  ${tokenNameToCssVar(token.name)}: ${token.value};`)
        varCount++
      }
    }
    lines.push('')
  }

  lines.push('}')

  const outputPath = path.join(LEDGER_DIR, 'tokens.css')
  writeFileSync(outputPath, lines.join('\n'))

  console.log(`[publish:css] Generated ${varCount} CSS variables from ${approvedTokens.length} tokens`)
  console.log(`[publish:css] Written to: ${outputPath}`)
}

main().catch(err => {
  console.error('[publish:css] Fatal:', err)
  process.exit(1)
})
